cloud:
  aws:
    region:
      static: us-east-1
      auto: false
    stack:
      auto: false
    credentials:
      access-key: AKIAWTLPDOJ753F7DMWN
      secret-key: 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
    end-point:
      uri: https://sqs.us-east-1.amazonaws.com/453888930431/Roman-Queue

